spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo?useSSL=false
    driver: com.mysql.cj.jdbc.Driver
    username: spring_demo_api
    password: spring_demo_api*12C

    hikari:
      maximum-pool-size: 10